djangorest/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('restaurants/',include('restaurants.urls')),
    path('admin/', admin.site.urls),
]

restaurants/urls.py
from django.urls import path
from . import  views
app_name = 'restaurants'
urlpatterns = [
    path('',views.showRestaurants, name = 'showrestaurants'),
    path('restaurant/new',views.newRestaurants,  name = 'newrestaurant'),
    path('restaurant/<int:restaurant_id>/edit',views.editRestaurant,  name = 'editrestaurant'),
    path('restaurant/<int:restaurant_id>/delete',views.deleteRestaurant, name = 'deleterestaurant'),
    path('restaurant/<int:restaurant_id>/menu',views.showMenu, name = 'showmenu'),
    path('restaurant/<int:restaurant_id>/menu/new',views.newMenuItem, name = 'newmenuitem'),
    path('restaurant/<int:restaurant_id>/menu/<int:menu_id>/edit',views.editMenuItem, name = 'editmenuitem'),
    path('restaurant/<int:restaurant_id>/menu/<int:menu_id>/delete',views.deleteMenuItem, name = 'deletemenuitem'),
    path('JSON',views.showRestaurantsJSON, name = 'showrestaurantsjson'),
    path('restaurant/<int:restaurant_id>/menu/JSON', views.showmenuJSON, name = 'showmenujson'),
    path('restaurant/<int:restaurant_id>/menu/<int:menu_id>/JSON', views.showMenuItemJSON, name = 'showmenuitemjson'),
               ]

restaurants/models.py
from django.db import models

# Create your models here.
class Restaurant(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=250)

    @property
    def serialize(self):
        return {
            'id': self.id,
            'name': self.name
        }

class MenuItem(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=80)
    description = models.CharField(max_length=250, null=True)
    price = models.CharField(max_length=8, null=True)
    course = models.CharField(max_length=250, null=True)
    restaurant_id = models.ForeignKey(Restaurant,on_delete=models.CASCADE)

    @property
    def serialize(self):
        #returns object data in easily serializable format
        return {'name':self.name,
                'description':self.description,
                'id':self.id,
                'price':self.price,
                'course':self.course
        }

restaurants/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from .models import Restaurant,MenuItem
from django.contrib import messages
from django.http import JsonResponse


def showRestaurants(request):
    restaurants = Restaurant.objects.all()
    return render(request, 'restaurants/restaurants.html', {'restaurants': restaurants})


def newRestaurants(request):
    if request.method == 'POST':
        newRest = Restaurant(name = request.POST['newrest'])
        newRest.save()
        messages.add_message(request, messages.SUCCESS,'Restaurant was created')
        return HttpResponseRedirect(reverse('restaurants:showrestaurants'))
    else:
        return render(request,'restaurants/newrestaurant.html')

def editRestaurant(request, restaurant_id):
    editedRestaurant = Restaurant.objects.get(id = restaurant_id)
    if request.method == 'POST':
        editedRestaurant.name = request.POST['editrest']
        editedRestaurant.save()
        messages.add_message(request,messages.SUCCESS, 'Restaurant was edited!')
        return HttpResponseRedirect(reverse('restaurants:showrestaurants'))
    else:
        return render(request,'restaurants/editrestaurant.html', {'restaurant': editedRestaurant})


def deleteRestaurant(request, restaurant_id):
    deletedRestaurant = Restaurant.objects.get(id = restaurant_id)
    if request.method == 'POST':
        deletedRestaurant.delete()
        messages.add_message(request, messages.SUCCESS, 'Restaurant was deleted!')
        return HttpResponseRedirect(reverse('restaurants:showrestaurants'))
    else:
        return render(request,'restaurants/deleterestaurant.html', {'restaurant' : deletedRestaurant})

def showMenu(request, restaurant_id):
    restaurant = Restaurant.objects.get(id = restaurant_id)
    items = MenuItem.objects.filter(restaurant_id = restaurant)
    return render(request, 'restaurants/menu.html', {'restaurant':restaurant, 'items': items})

def newMenuItem(request, restaurant_id):
    restaurant = Restaurant.objects.get(id = restaurant_id)
    if request.method == 'POST':
        newMenuItem = MenuItem(name = request.POST['namemenu'], description = request.POST['descripmenu'],
                               course = request.POST['coursemenu'], price = request.POST['pricemenu'],
                               restaurant_id = restaurant)
        newMenuItem.save()
        messages.add_message(request, messages.SUCCESS, 'Menu item was created!')
        return HttpResponseRedirect(reverse('restaurants:showmenu', args = [restaurant_id]))
    else:
        return render(request,'restaurants/newmenuitem.html', {'restaurant' :restaurant})

def editMenuItem(request, restaurant_id, menu_id):
    restaurant = Restaurant.objects.get(id = restaurant_id)
    editedMenu = MenuItem.objects.get(id = menu_id, restaurant_id = restaurant)
    if request.method == 'POST':
        if request.POST['namemenu']:
            editedMenu.name = request.POST['namemenu']
        if request.POST['descripmenu']:
            editedMenu.description = request.POST['descripmenu']
        if request.POST['coursemenu']:
            editedMenu.course = request.POST['coursemenu']
        if request.POST['pricemenu']:
            editedMenu.price = request.POST['pricemenu']
        editedMenu.save()
        messages.add_message(request, messages.SUCCESS, 'Menu item was edited')
        return HttpResponseRedirect(reverse('restaurants:showmenu', args = [restaurant_id]))
    else:
        return render(request,'restaurants/editmenuitem.html',{'restaurant' : restaurant, 'item' : editedMenu})

def deleteMenuItem(request, restaurant_id, menu_id):
    restaurant = Restaurant.objects.get(id = restaurant_id)
    deletedMenu = MenuItem.objects.get(id = menu_id, restaurant_id = restaurant)
    if request.method == 'POST':
        deletedMenu.delete()
        messages.add_message(request, messages.SUCCESS, 'Menu item deleted')
        return HttpResponseRedirect(reverse('restaurants:showmenu', args = [restaurant_id]))
    else:
        return render(request,'restaurants/deletemenuitem.html',{'restaurant' : restaurant, 'item' : deletedMenu})

#Api Endpoints
def showRestaurantsJSON(request):
    restaurants = Restaurant.objects.all()
    Restaurants = [restaurant.serialize for restaurant in restaurants]
    return JsonResponse(data= Restaurants, safe= False)

def showmenuJSON(request,restaurant_id):
    restaurant = Restaurant.objects.get(id = restaurant_id)
    items =  MenuItem.objects.filter(restaurant_id = restaurant)
    itemsjson = [item.serialize for item in items]
    return JsonResponse(data = itemsjson, safe = False)

def showMenuItemJSON(request, restaurant_id, menu_id):
    restaurant = Restaurant.objects.get(id = restaurant_id)
    item = MenuItem.objects.get(id = menu_id, restaurant_id = restaurant)
    itemjson = [item.serialize]
    return JsonResponse(data= itemjson, safe= False)

restaurants/templates/restaurants/deletemenuitem.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Menu Item</title>
</head>
<body>
	<h1>{{ restaurant.name }}</h1>
    <h2>Are you sure you want to delete </h2>
    <h2>{{ item.name }} ?</h2>
    <form action="{% url 'restaurants:deletemenuitem' restaurant.id item.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
        <a href="{% url 'restaurants:showmenu' restaurant.id %}">Cancel</a>
    </form>
</body>
</html>

restaurants/templates/restaurants/deleterestaurant.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Restaurant</title>
</head>
<body>
    <h1>Are you sure you want to delete </h1>
    <h1>{{ restaurant.name }} ?</h1>
    <form action="{% url 'restaurants:deleterestaurant' restaurant.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
        <a href="{% url 'restaurants:showrestaurants' %}">Cancel</a>
    </form>
</body>
</html>

restaurants/templates/restaurants/editmenuitem.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Menu Item</title>
</head>
<body>
	<h1>{{ restaurant.name }}</h1>
	<h2>Edit Menu Item</h2>
	<form action="{% url 'restaurants:editmenuitem' restaurant.id item.id  %}" method="post">
		{% csrf_token %}
        <p>Name: </p>
        <input type="text" name="namemenu" placeholder="{{ item.name }}">
		<p>Description: </p>
		<input type="text" name="descripmenu" placeholder="{{ item.description }}">
		<p>Price: </p>
		<input type="text" name="pricemenu" placeholder="{{ item.price }}">
		<p>Course: </p>
		<!-- add if and else in order to show default value -->
		{% if item.course == "Appetizer"%}
			<input type="radio" name="coursemenu" value="Appetizer" checked>Appetizer<br>
			<input type="radio" name="coursemenu" value="Entree" > Entree<br>
			<input type="radio" name="coursemenu" value="Dessert" > Dessert<br>
			<input type="radio" name="coursemenu" value="Beverage" > Beverage
		{% elif item.course == 'Entree' %}
			<input type="radio" name="coursemenu" value="Appetizer" >Appetizer<br>
			<input type="radio" name="coursemenu" value="Entree" checked> Entree<br>
			<input type="radio" name="coursemenu" value="Dessert" > Dessert<br>
			<input type="radio" name="coursemenu" value="Beverage" > Beverage
		{% elif item.course == 'Dessert' %}
			<input type="radio" name="coursemenu" value="Appetizer" >Appetizer<br>
			<input type="radio" name="coursemenu" value="Entree" > Entree<br>
			<input type="radio" name="coursemenu" value="Dessert" checked> Dessert<br>
			<input type="radio" name="coursemenu" value="Beverage" > Beverage
		{% elif item.course == 'Beverage' %}
			<input type="radio" name="coursemenu" value="Appetizer" >Appetizer<br>
			<input type="radio" name="coursemenu" value="Entree" > Entree<br>
			<input type="radio" name="coursemenu" value="Dessert" > Dessert<br>
			<input type="radio" name="coursemenu" value="Beverage" checked> Beverage
		{% endif %}

		<br><br>
		<br><br>
        <input type="submit" value="Edit">
        <a href="{% url 'restaurants:showmenu' restaurant.id %}">Cancel</a>
    </form>
</body>
</html>

restaurants/templates/restaurants/editrestaurant.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Restaurant</title>
</head>
<body>
    <h1>Edit Restaurant</h1>
    <form action="{% url 'restaurants:editrestaurant' restaurant.id %}" method="post">
        {% csrf_token %}
        <input type="text" name="editrest" placeholder="{{ restaurant.name }}">
        <input type="submit" value="Edit">
        <a href="{% url 'restaurants:showrestaurants' %}">Cancel</a>
    </form>
</body>
</html>

restaurants/templates/restaurants/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Menu</title>
</head>
<body>
	<h1>{{ restaurant.name }}'s Menu</h1>
	{% if messages %}
	<ul>
		{% for message in messages %}
		<li>{{ message }}</li>
		{% endfor %}
	{% endif %}
	<a href="{% url 'restaurants:newmenuitem' restaurant.id %}">Create a New Menu Item</a>
	{% for item in items %}
		<h2>{{ item.name }}</h2>
		<p>{{ item.course }}</p>
		<p>{{ item.price }}</p>
		<p>{{ item.description }}</p>
		<a href = "{% url 'restaurants:editmenuitem' restaurant.id item.id %}">Edit Menu Item</a>
		<a href = "{% url 'restaurants:deletemenuitem' restaurant.id item.id %}">Delete Menu Item</a>
	{% endfor %}
</body>
</html>

restaurants/templates/restaurants/newmenuitem.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Menu Item</title>
</head>
<body>
	<h1>{{ restaurant.name }}</h1>
    <h2>New Menu Item</h2>
    <form action="{% url 'restaurants:newmenuitem' restaurant.id %}" method="post">
        {% csrf_token %}
        <p>Name: </p>
        <input type="text" name="namemenu">
        <p>Description: </p>
		<input type="text" name="descripmenu">
		<p>Price: </p>
		<input type="text" name="pricemenu">
		<p>Course: </p>
		<input type="radio" name="coursemenu" value="Appetizer" checked>Appetizer<br>
        <input type="radio" name="coursemenu" value="Entree"> Entree<br>
        <input type="radio" name="coursemenu" value="Dessert"> Dessert<br>
        <input type="radio" name="coursemenu" value="Beverage"> Beverage
		<br><br>
        <input type="submit" value="Create">
        <a href="{% url 'restaurants:showmenu' restaurant.id %}">Cancel</a>
    </form>
</body>
</html>

restaurants/templates/restaurants/newrestaurant.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Restaurant</title>
</head>
<body>
    <h1>New Restaurant</h1>
    <form action="{% url 'restaurants:newrestaurant' %}" method="post">
        {% csrf_token %}
        <p>Name: </p>
        <input type="text" name="newrest">
        <input type="submit" value="New">
        <a href="{% url 'restaurants:showrestaurants' %}">Cancel</a>
    </form>
</body>
</html>

restaurants/templates/restaurants/restaurants.html
<!DOCTYPE html>
<html lang="eng">
<head>
	<meta charset="UTF-8">
	<title>Restaurants</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'restaurants/style.css' %}">
</head>
<body>
	<h1>RESTAURANTS</h1>
	{% if messages %}
	<ul>
		{% for message in messages %}
		<li>{{ message }}</li>
		{% endfor %}
	{% endif %}
	</ul>
		<a href="{% url 'restaurants:newrestaurant' %}">Create a New Restaurant</a>
	{% for rest in restaurants %}
		<h2>{{ rest.name }}</h2>
		<a href="{% url 'restaurants:showmenu' rest.id %}">Menu</a>
		<a href = "{% url 'restaurants:editrestaurant' rest.id %}">Edit Restaurant</a>
		<a href = "{% url 'restaurants:deleterestaurant' rest.id %}">Delete Restaurant</a>
	{% endfor %}
</body>
</html>